#!/bin/bash
export LANG=en_CA.UTF-8
export LC_TIME=en_DK.UTF-8
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
export HOME=/var/lib/plex
export LOGNAME=plex
export USER=plex
export SHELL=/usr/bin/nologin
export LD_LIBRARY_PATH=/opt/plexmediaserver
export PLEX_MEDIA_SERVER_HOME=/opt/plexmediaserver
export PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR=/var/lib/plex
export PLEX_MEDIA_SERVER_MAX_PLUGIN_PROCS=6
export PLEX_MEDIA_SERVER_TMPDIR=/tmp
export TMPDIR=/tmp

#export SHELL=/bin/bash
#export TMPDIR=/var/tmp
#export PLEX_MEDIA_SERVER_MAX_PLUGIN_PROCS=6
#export USER=plex
#export LD_LIBRARY_PATH=/opt/plexmediaserver
#export PLEX_MEDIA_SERVER_TMPDIR=/var/tmp
#export PLEX_MEDIA_SERVER_HOME=/opt/plexmediaserver
#export PLEX_MEDIA_SERVER_USER=plex
#export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
#export _=/opt/plexmediaserver/Plex Media Server
#export PWD=/opt/plexmediaserver
#export LANG=en_CA.UTF-8
#export PLEX_MEDIA_SERVER_MAX_STACK_SIZE=3000
#export HOME=/opt/plexmediaserver
#export SHLVL=2
#export LOGNAME=plex
#export PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR="/opt/plexmediaserver/Library/Application Support"
#export LC_TIME=en_DK.UTF-8



#export SHELL=/bin/bash
#export TMPDIR=/var/tmp
#export PLEX_MEDIA_SERVER_MAX_PLUGIN_PROCS=6
##export USER=plex
#export LD_LIBRARY_PATH=/opt/plexmediaserver
#export PLEX_MEDIA_SERVER_TMPDIR=/var/tmp
#export PLEX_MEDIA_SERVER_HOME=/opt/plexmediaserver
#export PLEX_MEDIA_SERVER_USER=plex
#export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
#export PWD=/opt/plexmediaserver
##export LANG=en_CA.UTF-8
#export PLEX_MEDIA_SERVER_MAX_STACK_SIZE=3000
#export HOME=/opt/plexmediaserver
#export SHLVL=2
#export LOGNAME=plex
#export PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR=/opt/plexmediaserver/Library/Application Support
##export LC_TIME=en_DK.UTF-8



#export SHELL=/bin/sh
#export TMPDIR=/tmp
#export PLEX_MEDIA_SERVER_MAX_PLUGIN_PROCS=6
#export USER=plex
#export LD_LIBRARY_PATH=/opt/plexmediaserver
#export PLEX_MEDIA_SERVER_TMPDIR=/var/tmp
#export PLEX_MEDIA_SERVER_HOME=/opt/plexmediaserver
#export PLEX_MEDIA_SERVER_USER=plex
#export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
##export _=/opt/plexmediaserver/Plex Media Server
#export PWD=/LANG=en_CA.UTF-8
#export PLEX_MEDIA_SERVER_MAX_STACK_SIZE=3000
#export HOME=/opt/plexmediaserver
#export SHLVL=2
#export LOGNAME=plex
#export PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR=/opt/plexmediaserver/var/lib/plexmediaserver
#export LC_TIME=en_DK.UTF-8
##export LD_LIBRARY_PATH=/opt/plexmediaserver
##export HOME=/opt/plexmediaserver/var/lib/plexmediaserver
##export PLEX_MEDIA_SERVER_TMPDIR=/var/tmp
##export PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR="/root/Library/Application Support"
##export PLEX_MEDIA_SERVER_MAX_STACK_SIZE=3000
##export PWD=/usr/lib/plexmediaserver
##export PLEX_MEDIA_SERVER_HOME=/home/plex/var/lib/plexmediaserver
##export PLEX_MEDIA_SERVER_MAX_PLUGIN_PROCS=6
/opt/plexmediaserver/Plex\ Media\ Scanner $@
