#!/bin/bash
export LANG=en_CA.UTF-8
export LC_TIME=en_DK.UTF-8
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
export HOME=/var/lib/plex
export LOGNAME=plex
export USER=plex
export SHELL=/usr/bin/nologin
export LD_LIBRARY_PATH=/opt/plexmediaserver
export PLEX_MEDIA_SERVER_HOME=/opt/plexmediaserver
export PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR=/var/lib/plex
export PLEX_MEDIA_SERVER_MAX_PLUGIN_PROCS=6
export PLEX_MEDIA_SERVER_TMPDIR=/tmp
export TMPDIR=/tmp

/opt/plexmediaserver/Plex\ Media\ Scanner $@
